resolver: lts-10.10

allow-newer: true

packages:
- '.'

- location:
    git: https://github.com/haskell-suite/haskell-tc.git
    commit: 3a893cb3fc844eea6e203d17e18f1f59cd14e5bf
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-scope.git
    commit: 5d77593110a0455745da4f376a5bcdb9e511784c
  extra-dep: true

extra-deps:
- haskell-src-exts-1.20.2
