resolver: lts-10.10

allow-newer: true

packages:
- '.'

- location:
    git: https://github.com/haskell-suite/haskell-tc.git
    commit: 24c4626668240d8ac0a586380a369be77e8b250c
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-scope.git
    commit: 5d77593110a0455745da4f376a5bcdb9e511784c
  extra-dep: true

extra-deps:
- haskell-src-exts-1.20.2
